apiVersion: v1
kind: Service
metadata:
  name: lab1-app
spec:
  selector:
    app: lab1-app
  ports:
  - protocol: "TCP"
    port: 9000
    targetPort: 9000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab1-app
spec:
  selector:
    matchLabels:
      app: lab1-app
  replicas: 1
  template:
    metadata:
      labels:
        app: lab1-app
    spec:
      containers:
      - name: lab1-app
        image: lab1-docker:good
        imagePullPolicy: Never
        ports:
        - containerPort: 9000