FROM python:3.10-slim-buster as builder
ARG PDM_VERSION=2.10.0
ENV PATH="/root/.local/bin:${PATH}"
RUN apt-get update && apt-get install -y curl && apt-get clean && rm -rf /var/lib/apt/lists/*
RUN curl -sSL https://pdm.fming.dev/install-pdm.py | python - --version="${PDM_VERSION}"
WORKDIR /project
COPY . .
RUN pdm install --global --project /project
RUN pdm cache clear
CMD ["python", "-m", "uvicorn", "src.main:app", "--port", "9001", "--host", "0.0.0.0"]